# Generated by Django 4.1.7 on 2023-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
